version: "2"
services:
  haproxy:
    container_name: 'haproxy'
    build: .
    ports:
      - '80:80'
      - '443:443'
      - '1936:1936'
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
      - ./ssl:/ssl
    restart: always